#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 11, 2017 01:42:59 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global combobox
    combobox = StringVar()
    global combobox2
    combobox2 = StringVar()
    global txtSAPVar
    txtSAPVar = StringVar()
    global lblCameraVar
    lblCameraVar = StringVar()
    global lblPrinterVar
    lblPrinterVar = StringVar()
    global ckBoxVar
    ckBoxVar = StringVar()
    global txtEndScreenDelayVar
    txtEndScreenDelayVar = StringVar()
    global txtPreviewScreenDelay
    txtPreviewScreenDelay = StringVar()

def onBtnCameraUpdate():
    lblCameraVar.set(camera.get_model())

def onBtnPrinterUpdate():
    print('settings_support.onBtnPrinterUpdate')
    sys.stdout.flush()

def onBtnSaveConfig():
    print('settings_support.onBtnSaveConfig')
    sys.stdout.flush()

def onBtnTakePhoto():
    print('settings_support.onBtnTakePhoto')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    
    txtSAPvar.set(2000)
    gui.cbPrintFormat['values'] = ('4x6', '2x6')
    #lblCameraVar.set(camera.get_model())

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import settings
    settings.vp_start_gui()


